"use client";

import { useState } from "react";
import { Activity, ArrowRight, Eye, EyeOff, LockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";

export default function AuthForm({ mode }: { mode: "login" | "register" }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [organizationName,setOrganizationName]=useState(""); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter();
  const register=mode==="register";
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch(`/api/auth/${register?"register":"login"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,...(register?{organizationName}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível entrar.");router.replace("/");router.refresh();}catch(err){setError(err instanceof Error?err.message:"Erro inesperado.");}finally{setBusy(false);}}
  return <main className="auth-page"><div className="auth-background"><i/><i/><i/></div><section className="auth-card"><div className="auth-brand"><div className="brand-mark"><Activity size={18} strokeWidth={2.8}/></div><span>pulso<span className="brand-dot">.</span></span></div><span className="auth-kicker">CENTRAL DE PUBLICAÇÃO</span><h1>{register?"Crie seu espaço":"Acesse seu espaço"}</h1><p className="auth-intro">{register?"Organize conteúdo e acompanhe suas contas em um só painel.":"Entre para gerenciar as publicações da sua organização."}</p><form onSubmit={submit} className="auth-form">{register&&<label>Nome da organização<input required minLength={2} maxLength={80} autoComplete="organization" value={organizationName} onChange={e=>setOrganizationName(e.target.value)} placeholder="Ex.: Aurora Studio"/></label>}<label>E-mail<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com"/></label><label>Senha<div className="password-field"><input type={showPassword?"text":"password"} required minLength={register?12:1} maxLength={128} autoComplete={register?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?"No mínimo 12 caracteres":"Sua senha"}/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?"Ocultar senha":"Mostrar senha"}>{showPassword?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{register&&<small>Use uma senha única com 12 caracteres ou mais.</small>}</label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?"Aguarde…":register?"Criar conta":"Entrar"}<ArrowRight size={16}/></button></form><div className="auth-divider"><span/></div><p className="auth-switch">{register?"Já tem uma conta?":"Ainda não tem uma conta?"} <a href={register?"/login":"/register"}>{register?"Entrar":"Criar espaço"}</a></p><div className="auth-security"><LockKeyhole size={13}/> Sessões protegidas · senhas armazenadas com Argon2id</div></section><footer className="auth-footer">Pulso Social · <span>Ambiente inicial sem conexão real com o Instagram</span></footer></main>;
}
